name: Build for Windows x64

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Set up Go
        uses: actions/setup-go
        with:
          go-version: '1.23.4'

      - name: Build for Windows x64
        run: |
          go build -ldflags="-s -w" -o goMH.exe

      - name: Upload artifact
        uses: actions/upload-artifact
        with:
          name: windows-x64-binary
          path: bin/goMH.exe