name: Build for Windows x64

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build for Windows x64
        run: |
          go build -o bin/goMH.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64-binary
          path: bin/goMH.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            Установщик ПО для MyHoreca.
            Версия: ${{ github.ref_name }}
          files: |
            bin/app.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}